name: Release
on:
  push:
    tags: ['[0-9]+.[0-9]+.[0-9]+']
    paths-ignore: [ 'docs/**' ]

permissions: write-all

jobs:
  build:
    runs-on: macos-latest
    environment: nuget
    env:
      SLN_FILE: NoSamples.sln
    steps:
    - uses: actions/checkout@v2
    - name: Extract version from tag
      uses: damienaicheh/extract-version-from-tag-action@v1.0.0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.401
    - name: Restore
      run: dotnet restore ${SLN_FILE}
    - name: Build
      run: dotnet build -p:Version="${MAJOR}.${MINOR}.${PATCH}" --no-restore --configuration Release ${SLN_FILE}
    - name: Test
      run: dotnet test -p:Version="${MAJOR}.${MINOR}.${PATCH}" --no-build --configuration Release ${SLN_FILE}
    - name: Pack
      run: |
        dotnet pack -p:Version="${MAJOR}.${MINOR}.${PATCH}" --configuration Release --output nupkgs ${SLN_FILE}
    - name: Push
      run: |
        dotnet nuget push "nupkgs/*.nupkg" -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_TOKEN }} --skip-duplicate